// <auto-generated />
using System;
using SkillBridge.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace SkillBridge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260219112019_DBseed")]
    partial class DBseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkillBridge.Models.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SkillId"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedAt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfReviews")
                        .HasColumnType("int");

                    b.Property<int>("PricePerHour")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("TeacherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SkillId");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            SkillId = 1,
                            Description = "Learn C# for Beginners",
                            NumberOfReviews = 347,
                            PricePerHour = 243,
                            Rating = 2.5,
                            TeacherId = 0,
                            TeacherName = "john",
                            Title = "C#"
                        },
                        new
                        {
                            SkillId = 2,
                            Description = "Learn ASP.NET Core",
                            NumberOfReviews = 200,
                            PricePerHour = 200,
                            Rating = 3.25,
                            TeacherId = 0,
                            TeacherName = "Doe",
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            SkillId = 3,
                            Description = "Learn Entity Framework",
                            NumberOfReviews = 150,
                            PricePerHour = 180,
                            Rating = 4.0,
                            TeacherId = 0,
                            TeacherName = "Doe",
                            Title = "Entity Framework"
                        },
                        new
                        {
                            SkillId = 4,
                            Description = "Learn JavaScript",
                            NumberOfReviews = 400,
                            PricePerHour = 220,
                            Rating = 5.0,
                            TeacherId = 0,
                            TeacherName = "Doe",
                            Title = "JavaScript"
                        },
                        new
                        {
                            SkillId = 5,
                            Description = "Learn Python",
                            NumberOfReviews = 500,
                            PricePerHour = 260,
                            Rating = 4.25,
                            TeacherId = 0,
                            TeacherName = "Doe",
                            Title = "Python"
                        },
                        new
                        {
                            SkillId = 6,
                            Description = "Learn Java",
                            NumberOfReviews = 300,
                            PricePerHour = 240,
                            Rating = 1.5700000000000001,
                            TeacherId = 0,
                            TeacherName = "Doe",
                            Title = "Java"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
